program: train.py
method: bayes
metric:
  name: validation_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  num_epochs:
    min: 1
    max: 10
  batch_size:
    min: 16
    max: 512
  learning_rate:
    min: 0.0001
    max: 0.1
  optimizer:
    values: ["Adam", "SGD"]

command:
  - ${env}
  - poetry 
  - run 
  - python
  - ${program}
  - ${args}